### ISSUE TITLE
Onomastic Analysis New Structure

### ISSUE THREAD

**Issue by lmischer** [EIS1600/eis1600-pkg#5]
Extract onomastic information in the following way:
```
- ism: name
- nas:
    1: full name father
    2: full name grandfather
    x: full name xth ancestor
- lqb: laqab
- kun: kunya
- nsb: [nsb1, nsb2, nsbx]
```

Information in a way that allows for the identification of biographies of the same individual
